### ISSUE TITLE
Not working for Cryptomator-bin 1.5.17-1 on Manjaro

### ISSUE THREAD

**Issue by blogdemoi** [purejava/keepassxc-proxy-access#2]
Hi,
I installed Cryptomator with AUR and copied the.jar file in /home/xxx/.local/share/Cryptomator/plugins/ but nothing happens.
I tried to install Cryptomator 1.5.17-1 (not -bin) but it didn't install so I had no choice than installing the -bin release.
Any suggestions.
Thank you.

**Comment by purejava** [comment]
Hi,

Cryptomator needs the ability to load plugins from the plugin directory in order to use keepassxc-proxy-access. This functionality is available since Cryptomator [release 1.6.0 Beta 2](https://github.com/cryptomator/cryptomator/releases/tag/1.6.0-beta2). Cryptomator 1.5.17 does not include the required functionality.

For  Cryptomator release 1.6.0 Beta 2 there is an AppImage available you can try.

**Comment by blogdemoi** [comment]
> For Cryptomator release 1.6.0 Beta 2 there is an AppImage available you can try.

Thank you, it is working now!
